cache op session

diff --git a/exec/op-assume b/exec/op-assume
--- a/exec/op-assume
+++ b/exec/op-assume
@@ -8,7 +8,27 @@ function main {
 
   local nm_account="$1"; shift
 
-  export "OP_SESSION_${nm_account}"="$(gpg2 -q -d "${BOARD_PATH}/.op/${nm_account}.gpg" | op signin "${nm_account}" --output=raw)"
+  local pth_session="${BOARD_PATH}/.op/session-${nm_account}.gpg"
+
+  local attempts=1
+  while true; do
+    if [[ ! -f "$pth_session" ]]; then
+      gpg2 -q -d "${BOARD_PATH}/.op/${nm_account}.gpg" | op signin "${nm_account}" --output=raw | gpg2 -e -a -r "$(gpg2 --card-status 2>&1 | grep 'General key info' | awk '{print $NF}' | cut -d'<' -f2 | cut -d'>' -f1)" > "$pth_session"
+    fi
+
+    export "OP_SESSION_${nm_account}"="$(gpg2 -q -d "$pth_session")"
+
+    if op get vault "meh-$$" 2>&1 | grep "Vault meh-$$ not found"; then
+      break
+    fi
+
+    rm -f "${pth_session}"
+    attempts="$((attempts + 1))"
+    if [[ "$attempts" -gt 2 ]]; then
+      echo "ERROR: unable to get a valid 1Password session" 1>&2
+      exit 2
+    fi
+  done
   
   if [[ "$#" == 0 ]]; then
     exec "$SHELL"
